### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by nokky-en298** [nokky-en298/furima-33538#9]
#URL
https://furima-33538.herokuapp.com/

#Basic認証のIDとパスワード
ID: basnoki
パスワード: 3452

#出品者用のメールアドレスとパスワード
メールアドレス: jirou@com
パスワード: jirou777

#購入者用のメールアドレスとパスワード
メールアドレス: makoto@com
パスワード: makoto777

#購入用カードの番号・期限・セキュリティコード
番号:4242424242424242
期限:3月33年
セキュリティコード:123

**Comment by takumi0530** [comment]
@nokky-en298 さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![103257092-230e5100-49d3-11eb-8c1c-6c581ac15ae9](https://user-images.githubusercontent.com/76197191/106564314-6c246880-6570-11eb-8ffa-c44079797153.png)

**Comment by nokky-en298** [comment]
ありがとうございます。
これからも頑張ります！
